/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.models.components.CustomsItemBase;
import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class CreateCustomsItemRequestBuilder {

    private Optional<String> shippoApiVersion = Optional.empty();
    private CustomsItemBase customsItemBase;
    private final SDKMethodInterfaces.MethodCallCreateCustomsItem sdk;

    public CreateCustomsItemRequestBuilder(SDKMethodInterfaces.MethodCallCreateCustomsItem sdk) {
        this.sdk = sdk;
    }
                
    public CreateCustomsItemRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public CreateCustomsItemRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public CreateCustomsItemRequestBuilder customsItemBase(com.shippo.sdk.models.components.CustomsItemBase customsItemBase) {
        Utils.checkNotNull(customsItemBase, "customsItemBase");
        this.customsItemBase = customsItemBase;
        return this;
    }

    public CreateCustomsItemResponse call() throws Exception {

        return sdk.create(
            shippoApiVersion,
            customsItemBase);
    }
}
