/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.models.components.ShippoAccountUpdateRequest;
import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class CreateShippoAccountRequestBuilder {

    private Optional<String> shippoApiVersion = Optional.empty();
    private ShippoAccountUpdateRequest shippoAccountUpdateRequest;
    private final SDKMethodInterfaces.MethodCallCreateShippoAccount sdk;

    public CreateShippoAccountRequestBuilder(SDKMethodInterfaces.MethodCallCreateShippoAccount sdk) {
        this.sdk = sdk;
    }
                
    public CreateShippoAccountRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public CreateShippoAccountRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public CreateShippoAccountRequestBuilder shippoAccountUpdateRequest(com.shippo.sdk.models.components.ShippoAccountUpdateRequest shippoAccountUpdateRequest) {
        Utils.checkNotNull(shippoAccountUpdateRequest, "shippoAccountUpdateRequest");
        this.shippoAccountUpdateRequest = shippoAccountUpdateRequest;
        return this;
    }

    public CreateShippoAccountResponse call() throws Exception {

        return sdk.create(
            shippoApiVersion,
            shippoAccountUpdateRequest);
    }
}
