/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.models.components.ManifestCreateRequest;
import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class CreateManifestRequestBuilder {

    private Optional<String> shippoApiVersion = Optional.empty();
    private ManifestCreateRequest manifestCreateRequest;
    private final SDKMethodInterfaces.MethodCallCreateManifest sdk;

    public CreateManifestRequestBuilder(SDKMethodInterfaces.MethodCallCreateManifest sdk) {
        this.sdk = sdk;
    }
                
    public CreateManifestRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public CreateManifestRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public CreateManifestRequestBuilder manifestCreateRequest(com.shippo.sdk.models.components.ManifestCreateRequest manifestCreateRequest) {
        Utils.checkNotNull(manifestCreateRequest, "manifestCreateRequest");
        this.manifestCreateRequest = manifestCreateRequest;
        return this;
    }

    public CreateManifestResponse call() throws Exception {

        return sdk.create(
            shippoApiVersion,
            manifestCreateRequest);
    }
}
