/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.shippo.sdk.models.components.CustomsItemBase;
import com.shippo.sdk.utils.SpeakeasyMetadata;
import com.shippo.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;


public class CreateCustomsItemRequest {

    /**
     * String used to pick a non-default API version to use
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=SHIPPO-API-VERSION")
    private Optional<String> shippoApiVersion;

    /**
     * CustomsItem details.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private CustomsItemBase customsItemBase;

    @JsonCreator
    public CreateCustomsItemRequest(
            Optional<String> shippoApiVersion,
            CustomsItemBase customsItemBase) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        Utils.checkNotNull(customsItemBase, "customsItemBase");
        this.shippoApiVersion = shippoApiVersion;
        this.customsItemBase = customsItemBase;
    }
    
    public CreateCustomsItemRequest(
            CustomsItemBase customsItemBase) {
        this(Optional.empty(), customsItemBase);
    }

    /**
     * String used to pick a non-default API version to use
     */
    @JsonIgnore
    public Optional<String> shippoApiVersion() {
        return shippoApiVersion;
    }

    /**
     * CustomsItem details.
     */
    @JsonIgnore
    public CustomsItemBase customsItemBase() {
        return customsItemBase;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * String used to pick a non-default API version to use
     */
    public CreateCustomsItemRequest withShippoApiVersion(String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
        return this;
    }

    /**
     * String used to pick a non-default API version to use
     */
    public CreateCustomsItemRequest withShippoApiVersion(Optional<String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    /**
     * CustomsItem details.
     */
    public CreateCustomsItemRequest withCustomsItemBase(CustomsItemBase customsItemBase) {
        Utils.checkNotNull(customsItemBase, "customsItemBase");
        this.customsItemBase = customsItemBase;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCustomsItemRequest other = (CreateCustomsItemRequest) o;
        return 
            Objects.deepEquals(this.shippoApiVersion, other.shippoApiVersion) &&
            Objects.deepEquals(this.customsItemBase, other.customsItemBase);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            shippoApiVersion,
            customsItemBase);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCustomsItemRequest.class,
                "shippoApiVersion", shippoApiVersion,
                "customsItemBase", customsItemBase);
    }
    
    public final static class Builder {
 
        private Optional<String> shippoApiVersion = Optional.empty();
 
        private CustomsItemBase customsItemBase;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(String shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
            return this;
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(Optional<String> shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = shippoApiVersion;
            return this;
        }

        /**
         * CustomsItem details.
         */
        public Builder customsItemBase(CustomsItemBase customsItemBase) {
            Utils.checkNotNull(customsItemBase, "customsItemBase");
            this.customsItemBase = customsItemBase;
            return this;
        }
        
        public CreateCustomsItemRequest build() {
            return new CreateCustomsItemRequest(
                shippoApiVersion,
                customsItemBase);
        }
    }
}

