/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetCarrierRegistrationStatusRequestBuilder {

    private Carrier carrier;
    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetCarrierRegistrationStatus sdk;

    public GetCarrierRegistrationStatusRequestBuilder(SDKMethodInterfaces.MethodCallGetCarrierRegistrationStatus sdk) {
        this.sdk = sdk;
    }

    public GetCarrierRegistrationStatusRequestBuilder carrier(com.shippo.sdk.models.operations.Carrier carrier) {
        Utils.checkNotNull(carrier, "carrier");
        this.carrier = carrier;
        return this;
    }
                
    public GetCarrierRegistrationStatusRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public GetCarrierRegistrationStatusRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public GetCarrierRegistrationStatusResponse call() throws Exception {

        return sdk.getRegistrationStatus(
            carrier,
            shippoApiVersion);
    }
}
