/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetParcelRequestBuilder {

    private String parcelId;
    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetParcel sdk;

    public GetParcelRequestBuilder(SDKMethodInterfaces.MethodCallGetParcel sdk) {
        this.sdk = sdk;
    }

    public GetParcelRequestBuilder parcelId(java.lang.String parcelId) {
        Utils.checkNotNull(parcelId, "parcelId");
        this.parcelId = parcelId;
        return this;
    }
                
    public GetParcelRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public GetParcelRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public GetParcelResponse call() throws Exception {

        return sdk.get(
            parcelId,
            shippoApiVersion);
    }
}
