/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetShippoAccountRequestBuilder {

    private String shippoAccountId;
    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetShippoAccount sdk;

    public GetShippoAccountRequestBuilder(SDKMethodInterfaces.MethodCallGetShippoAccount sdk) {
        this.sdk = sdk;
    }

    public GetShippoAccountRequestBuilder shippoAccountId(java.lang.String shippoAccountId) {
        Utils.checkNotNull(shippoAccountId, "shippoAccountId");
        this.shippoAccountId = shippoAccountId;
        return this;
    }
                
    public GetShippoAccountRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public GetShippoAccountRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public GetShippoAccountResponse call() throws Exception {

        return sdk.get(
            shippoAccountId,
            shippoApiVersion);
    }
}
