/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetTrackRequestBuilder {

    private String trackingNumber;
    private String carrier;
    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetTrack sdk;

    public GetTrackRequestBuilder(SDKMethodInterfaces.MethodCallGetTrack sdk) {
        this.sdk = sdk;
    }

    public GetTrackRequestBuilder trackingNumber(java.lang.String trackingNumber) {
        Utils.checkNotNull(trackingNumber, "trackingNumber");
        this.trackingNumber = trackingNumber;
        return this;
    }

    public GetTrackRequestBuilder carrier(java.lang.String carrier) {
        Utils.checkNotNull(carrier, "carrier");
        this.carrier = carrier;
        return this;
    }
                
    public GetTrackRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public GetTrackRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public GetTrackResponse call() throws Exception {

        return sdk.get(
            trackingNumber,
            carrier,
            shippoApiVersion);
    }
}
