/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetUserParcelTemplateRequestBuilder {

    private String userParcelTemplateObjectId;
    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetUserParcelTemplate sdk;

    public GetUserParcelTemplateRequestBuilder(SDKMethodInterfaces.MethodCallGetUserParcelTemplate sdk) {
        this.sdk = sdk;
    }

    public GetUserParcelTemplateRequestBuilder userParcelTemplateObjectId(java.lang.String userParcelTemplateObjectId) {
        Utils.checkNotNull(userParcelTemplateObjectId, "userParcelTemplateObjectId");
        this.userParcelTemplateObjectId = userParcelTemplateObjectId;
        return this;
    }
                
    public GetUserParcelTemplateRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public GetUserParcelTemplateRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public GetUserParcelTemplateResponse call() throws Exception {

        return sdk.get(
            userParcelTemplateObjectId,
            shippoApiVersion);
    }
}
