/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class ListServiceGroupsRequestBuilder {

    private Optional<String> shippoApiVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListServiceGroups sdk;

    public ListServiceGroupsRequestBuilder(SDKMethodInterfaces.MethodCallListServiceGroups sdk) {
        this.sdk = sdk;
    }
                
    public ListServiceGroupsRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public ListServiceGroupsRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }

    public ListServiceGroupsResponse call() throws Exception {

        return sdk.list(
            shippoApiVersion);
    }
}
