/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.models.components.AddressCreateRequest;
import com.shippo.sdk.models.components.BatchCreateRequest;
import com.shippo.sdk.models.components.BatchShipmentCreateRequest;
import com.shippo.sdk.models.components.CarrierAccountBase;
import com.shippo.sdk.models.components.ConnectExistingOwnAccountRequest;
import com.shippo.sdk.models.components.CustomsDeclarationCreateRequest;
import com.shippo.sdk.models.components.CustomsItemBase;
import com.shippo.sdk.models.components.DefaultParcelTemplateUpdateRequest;
import com.shippo.sdk.models.components.LiveRateCreateRequest;
import com.shippo.sdk.models.components.ManifestCreateRequest;
import com.shippo.sdk.models.components.OrderCreateRequest;
import com.shippo.sdk.models.components.PickupBase;
import com.shippo.sdk.models.components.RefundRequestBody;
import com.shippo.sdk.models.components.ServiceGroupCreateRequest;
import com.shippo.sdk.models.components.ServiceGroupUpdateRequest;
import com.shippo.sdk.models.components.ShipmentCreateRequest;
import com.shippo.sdk.models.components.ShippoAccountUpdateRequest;
import com.shippo.sdk.models.components.TracksRequest;
import com.shippo.sdk.models.components.UserParcelTemplateCreateRequest;
import com.shippo.sdk.models.components.UserParcelTemplateUpdateRequest;
import com.shippo.sdk.models.components.WebhookUpdateRequest;
import java.lang.Long;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public class SDKMethodInterfaces {


    public interface MethodCallListAddresses {
        com.shippo.sdk.models.operations.ListAddressesResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateAddress {
        com.shippo.sdk.models.operations.CreateAddressResponse create(
            Optional<String> shippoApiVersion,
            AddressCreateRequest addressCreateRequest) throws Exception;
    }


    public interface MethodCallGetAddress {
        com.shippo.sdk.models.operations.GetAddressResponse get(
            String addressId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallValidateAddress {
        com.shippo.sdk.models.operations.ValidateAddressResponse validate(
            String addressId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateBatch {
        com.shippo.sdk.models.operations.CreateBatchResponse create(
            Optional<String> shippoApiVersion,
            BatchCreateRequest batchCreateRequest) throws Exception;
    }


    public interface MethodCallGetBatch {
        com.shippo.sdk.models.operations.GetBatchResponse get(
            String batchId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallAddShipmentsToBatch {
        com.shippo.sdk.models.operations.AddShipmentsToBatchResponse addShipments(
            String batchId,
            Optional<String> shippoApiVersion,
            List<BatchShipmentCreateRequest> requestBody) throws Exception;
    }


    public interface MethodCallPurchaseBatch {
        com.shippo.sdk.models.operations.PurchaseBatchResponse purchase(
            String batchId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallRemoveShipmentsFromBatch {
        com.shippo.sdk.models.operations.RemoveShipmentsFromBatchResponse removeShipments(
            String batchId,
            Optional<String> shippoApiVersion,
            List<String> requestBody) throws Exception;
    }


    public interface MethodCallListCarrierAccounts {
        com.shippo.sdk.models.operations.ListCarrierAccountsResponse list(
            ListCarrierAccountsRequest request) throws Exception;
    }


    public interface MethodCallCreateCarrierAccount {
        com.shippo.sdk.models.operations.CreateCarrierAccountResponse create(
            Optional<String> shippoApiVersion,
            ConnectExistingOwnAccountRequest connectExistingOwnAccountRequest) throws Exception;
    }


    public interface MethodCallGetCarrierAccount {
        com.shippo.sdk.models.operations.GetCarrierAccountResponse get(
            String carrierAccountId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallUpdateCarrierAccount {
        com.shippo.sdk.models.operations.UpdateCarrierAccountResponse update(
            String carrierAccountId,
            Optional<String> shippoApiVersion,
            Optional<? extends CarrierAccountBase> carrierAccountBase) throws Exception;
    }


    public interface MethodCallInitiateOauth2Signin {
        com.shippo.sdk.models.operations.InitiateOauth2SigninResponse initiateOauth2Signin(
            String carrierAccountObjectId,
            String redirectUri,
            Optional<String> state,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallRegisterCarrierAccount {
        com.shippo.sdk.models.operations.RegisterCarrierAccountResponse register(
            Optional<String> shippoApiVersion,
            RegisterCarrierAccountRequestBody requestBody) throws Exception;
    }


    public interface MethodCallGetCarrierRegistrationStatus {
        com.shippo.sdk.models.operations.GetCarrierRegistrationStatusResponse getRegistrationStatus(
            Carrier carrier,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListCustomsDeclarations {
        com.shippo.sdk.models.operations.ListCustomsDeclarationsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateCustomsDeclaration {
        com.shippo.sdk.models.operations.CreateCustomsDeclarationResponse create(
            Optional<String> shippoApiVersion,
            CustomsDeclarationCreateRequest customsDeclarationCreateRequest) throws Exception;
    }


    public interface MethodCallGetCustomsDeclaration {
        com.shippo.sdk.models.operations.GetCustomsDeclarationResponse get(
            String customsDeclarationId,
            Optional<Long> page,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListCustomsItems {
        com.shippo.sdk.models.operations.ListCustomsItemsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateCustomsItem {
        com.shippo.sdk.models.operations.CreateCustomsItemResponse create(
            Optional<String> shippoApiVersion,
            CustomsItemBase customsItemBase) throws Exception;
    }


    public interface MethodCallGetCustomsItem {
        com.shippo.sdk.models.operations.GetCustomsItemResponse get(
            String customsItemId,
            Optional<Long> page,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateLiveRate {
        com.shippo.sdk.models.operations.CreateLiveRateResponse create(
            Optional<String> shippoApiVersion,
            LiveRateCreateRequest liveRateCreateRequest) throws Exception;
    }


    public interface MethodCallGetDefaultParcelTemplate {
        com.shippo.sdk.models.operations.GetDefaultParcelTemplateResponse getDefaultParcelTemplate(
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallUpdateDefaultParcelTemplate {
        com.shippo.sdk.models.operations.UpdateDefaultParcelTemplateResponse updateDefaultParcelTemplate(
            Optional<String> shippoApiVersion,
            Optional<? extends DefaultParcelTemplateUpdateRequest> defaultParcelTemplateUpdateRequest) throws Exception;
    }


    public interface MethodCallDeleteDefaultParcelTemplate {
        com.shippo.sdk.models.operations.DeleteDefaultParcelTemplateResponse deleteDefaultParcelTemplate(
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListManifests {
        com.shippo.sdk.models.operations.ListManifestsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateManifest {
        com.shippo.sdk.models.operations.CreateManifestResponse create(
            Optional<String> shippoApiVersion,
            ManifestCreateRequest manifestCreateRequest) throws Exception;
    }


    public interface MethodCallGetManifest {
        com.shippo.sdk.models.operations.GetManifestResponse get(
            String manifestId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListOrders {
        com.shippo.sdk.models.operations.ListOrdersResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateOrder {
        com.shippo.sdk.models.operations.CreateOrderResponse create(
            Optional<String> shippoApiVersion,
            OrderCreateRequest orderCreateRequest) throws Exception;
    }


    public interface MethodCallGetOrder {
        com.shippo.sdk.models.operations.GetOrderResponse get(
            String orderId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListCarrierParcelTemplates {
        com.shippo.sdk.models.operations.ListCarrierParcelTemplatesResponse list(
            Optional<? extends Include> include,
            Optional<String> carrier,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallGetCarrierParcelTemplate {
        com.shippo.sdk.models.operations.GetCarrierParcelTemplateResponse get(
            String carrierParcelTemplateToken,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListParcels {
        com.shippo.sdk.models.operations.ListParcelsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateParcel {
        com.shippo.sdk.models.operations.CreateParcelResponse create(
            Optional<String> shippoApiVersion,
            CreateParcelRequestBody requestBody) throws Exception;
    }


    public interface MethodCallGetParcel {
        com.shippo.sdk.models.operations.GetParcelResponse get(
            String parcelId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreatePickup {
        com.shippo.sdk.models.operations.CreatePickupResponse create(
            Optional<String> shippoApiVersion,
            PickupBase pickupBase) throws Exception;
    }


    public interface MethodCallGetRate {
        com.shippo.sdk.models.operations.GetRateResponse get(
            String rateId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListShipmentRates {
        com.shippo.sdk.models.operations.ListShipmentRatesResponse listShipmentRates(
            String shipmentId,
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListShipmentRatesByCurrencyCode {
        com.shippo.sdk.models.operations.ListShipmentRatesByCurrencyCodeResponse listShipmentRatesByCurrencyCode(
            ListShipmentRatesByCurrencyCodeRequest request) throws Exception;
    }


    public interface MethodCallCreateRefund {
        com.shippo.sdk.models.operations.CreateRefundResponse create(
            Optional<String> shippoApiVersion,
            RefundRequestBody refundRequestBody) throws Exception;
    }


    public interface MethodCallListRefunds {
        com.shippo.sdk.models.operations.ListRefundsResponse list(
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallGetRefund {
        com.shippo.sdk.models.operations.GetRefundResponse get(
            String refundId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListServiceGroups {
        com.shippo.sdk.models.operations.ListServiceGroupsResponse list(
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateServiceGroup {
        com.shippo.sdk.models.operations.CreateServiceGroupResponse create(
            Optional<String> shippoApiVersion,
            ServiceGroupCreateRequest serviceGroupCreateRequest) throws Exception;
    }


    public interface MethodCallUpdateServiceGroup {
        com.shippo.sdk.models.operations.UpdateServiceGroupResponse update(
            Optional<String> shippoApiVersion,
            Optional<? extends ServiceGroupUpdateRequest> serviceGroupUpdateRequest) throws Exception;
    }


    public interface MethodCallDeleteServiceGroup {
        com.shippo.sdk.models.operations.DeleteServiceGroupResponse delete(
            String serviceGroupId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListShipments {
        com.shippo.sdk.models.operations.ListShipmentsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateShipment {
        com.shippo.sdk.models.operations.CreateShipmentResponse create(
            Optional<String> shippoApiVersion,
            ShipmentCreateRequest shipmentCreateRequest) throws Exception;
    }


    public interface MethodCallGetShipment {
        com.shippo.sdk.models.operations.GetShipmentResponse get(
            String shipmentId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateTrack {
        com.shippo.sdk.models.operations.CreateTrackResponse create(
            Optional<String> shippoApiVersion,
            TracksRequest tracksRequest) throws Exception;
    }


    public interface MethodCallGetTrack {
        com.shippo.sdk.models.operations.GetTrackResponse get(
            String trackingNumber,
            String carrier,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListTransactions {
        com.shippo.sdk.models.operations.ListTransactionsResponse list(
            ListTransactionsRequest request) throws Exception;
    }


    public interface MethodCallCreateTransaction {
        com.shippo.sdk.models.operations.CreateTransactionResponse create(
            Optional<String> shippoApiVersion,
            CreateTransactionRequestBody requestBody) throws Exception;
    }


    public interface MethodCallGetTransaction {
        com.shippo.sdk.models.operations.GetTransactionResponse get(
            String transactionId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallListUserParcelTemplates {
        com.shippo.sdk.models.operations.ListUserParcelTemplatesResponse list(
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateUserParcelTemplate {
        com.shippo.sdk.models.operations.CreateUserParcelTemplateResponse create(
            Optional<String> shippoApiVersion,
            UserParcelTemplateCreateRequest userParcelTemplateCreateRequest) throws Exception;
    }


    public interface MethodCallDeleteUserParcelTemplate {
        com.shippo.sdk.models.operations.DeleteUserParcelTemplateResponse delete(
            String userParcelTemplateObjectId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallGetUserParcelTemplate {
        com.shippo.sdk.models.operations.GetUserParcelTemplateResponse get(
            String userParcelTemplateObjectId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallUpdateUserParcelTemplate {
        com.shippo.sdk.models.operations.UpdateUserParcelTemplateResponse update(
            String userParcelTemplateObjectId,
            Optional<String> shippoApiVersion,
            Optional<? extends UserParcelTemplateUpdateRequest> userParcelTemplateUpdateRequest) throws Exception;
    }


    public interface MethodCallListShippoAccounts {
        com.shippo.sdk.models.operations.ListShippoAccountsResponse list(
            Optional<Long> page,
            Optional<Long> results,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallCreateShippoAccount {
        com.shippo.sdk.models.operations.CreateShippoAccountResponse create(
            Optional<String> shippoApiVersion,
            ShippoAccountUpdateRequest shippoAccountUpdateRequest) throws Exception;
    }


    public interface MethodCallGetShippoAccount {
        com.shippo.sdk.models.operations.GetShippoAccountResponse get(
            String shippoAccountId,
            Optional<String> shippoApiVersion) throws Exception;
    }


    public interface MethodCallUpdateShippoAccount {
        com.shippo.sdk.models.operations.UpdateShippoAccountResponse update(
            String shippoAccountId,
            Optional<String> shippoApiVersion,
            Optional<? extends ShippoAccountUpdateRequest> shippoAccountUpdateRequest) throws Exception;
    }


    public interface MethodCallCreateWebhook {
        com.shippo.sdk.models.operations.CreateWebhookResponse createWebhook(
            WebhookUpdateRequest request) throws Exception;
    }


    public interface MethodCallListWebhooks {
        com.shippo.sdk.models.operations.ListWebhooksResponse listWebhooksDirect() throws Exception;
    }


    public interface MethodCallGetWebhook {
        com.shippo.sdk.models.operations.GetWebhookResponse getWebhook(
            String webhookId) throws Exception;
    }


    public interface MethodCallUpdateWebhook {
        com.shippo.sdk.models.operations.UpdateWebhookResponse updateWebhook(
            String webhookId,
            WebhookUpdateRequest webhookUpdateRequest) throws Exception;
    }


    public interface MethodCallDeleteWebhook {
        com.shippo.sdk.models.operations.DeleteWebhookResponse deleteWebhook(
            String webhookId) throws Exception;
    }


}
