/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;

import com.shippo.sdk.models.components.CarrierAccountBase;
import com.shippo.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class UpdateCarrierAccountRequestBuilder {

    private String carrierAccountId;
    private Optional<String> shippoApiVersion = Optional.empty();
    private Optional<? extends CarrierAccountBase> carrierAccountBase = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateCarrierAccount sdk;

    public UpdateCarrierAccountRequestBuilder(SDKMethodInterfaces.MethodCallUpdateCarrierAccount sdk) {
        this.sdk = sdk;
    }

    public UpdateCarrierAccountRequestBuilder carrierAccountId(java.lang.String carrierAccountId) {
        Utils.checkNotNull(carrierAccountId, "carrierAccountId");
        this.carrierAccountId = carrierAccountId;
        return this;
    }
                
    public UpdateCarrierAccountRequestBuilder shippoApiVersion(java.lang.String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.of(shippoApiVersion);
        return this;
    }

    public UpdateCarrierAccountRequestBuilder shippoApiVersion(java.util.Optional<java.lang.String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }
                
    public UpdateCarrierAccountRequestBuilder carrierAccountBase(com.shippo.sdk.models.components.CarrierAccountBase carrierAccountBase) {
        Utils.checkNotNull(carrierAccountBase, "carrierAccountBase");
        this.carrierAccountBase = Optional.of(carrierAccountBase);
        return this;
    }

    public UpdateCarrierAccountRequestBuilder carrierAccountBase(java.util.Optional<? extends com.shippo.sdk.models.components.CarrierAccountBase> carrierAccountBase) {
        Utils.checkNotNull(carrierAccountBase, "carrierAccountBase");
        this.carrierAccountBase = carrierAccountBase;
        return this;
    }

    public UpdateCarrierAccountResponse call() throws Exception {

        return sdk.update(
            carrierAccountId,
            shippoApiVersion,
            carrierAccountBase);
    }
}
