/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * ServiceLevelMaergoEnum - |Token | Service name|
 * |:---|:---|
 * | x_delivery_expedited | Expedited|
 * 
 */
public enum ServiceLevelMaergoEnum {
    X_DELIVERY_EXPEDITED("x_delivery_expedited");

    @JsonValue
    private final String value;

    private ServiceLevelMaergoEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
